# Generated by Django 4.2.7 on 2023-12-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='content',
        ),
    ]
